version: '4.0'
name: '3495'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: data_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - default

  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=mysecretkey
    depends_on:
      - mysql
    entrypoint: ["dockerize", "-wait", "tcp://mysql:3306", "-timeout", "60s", "python", "app.py"]
    networks:
      - default

  enter-data:
    build: ./enter-data
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - mysql
    environment:
      MYSQL_HOST: mysql
    entrypoint: ["dockerize", "-wait", "tcp://mysql:3306", "-timeout", "60s", "npm", "start"]
    networks:
      - default

  analytics-service:
    build: ./analytics-service
    ports:
      - "5001:5001"
    depends_on:
      - mysql
      - mongodb
    entrypoint: ["dockerize", "-wait", "tcp://mysql:3306", "-timeout", "60s", "python", "app.py"]
    networks:
      - default

  show-results:
    build: ./show-results
    ports:
      - "3001:3001"
    depends_on:
      - auth-service
      - mongodb
    entrypoint: ["dockerize", "-wait", "tcp://mysql:3306", "-timeout", "60s", "node", "server.js"]
    networks:
      - default
    

volumes:
  mysql_data:
  mongo_data:

networks:
  default:
    driver: bridge
