apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-results
spec:
  replicas: 2
  selector:
    matchLabels:
      app: show-results
  template:
    metadata:
      labels:
        app: show-results
    spec:
      containers:
      - name: show-results
        image: juantarigan/3495-show-results:latest 
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          value: mongodb://mongodb:27017
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
