apiVersion: apps/v1
kind: Deployment
metadata:
  name: enter-data
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enter-data
  template:
    metadata:
      labels:
        app: enter-data
    spec:
      containers:
      - name: enter-data
        image: juantarigan/3495-enter-data:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: user
        - name: DB_PASSWORD
          value: pass
        - name: DB_NAME
          value: mydb
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
